apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcm-demo-consumer-customers-activation
  labels:
    k8s-app: mcm-demo-consumer-customers-activation
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: mcm-demo-consumer-customers-activation
  template:
    metadata:
      labels:
        k8s-app: mcm-demo-consumer-customers-activation
    spec:
      imagePullSecrets:
      - name: registrykey
      containers:
      - name: mcm-demo-consumer-customers-activation
        image: labcabrera/mcm-demo-consumer-customers-activation:latest
        env:
        - name: APP_KAFKA_BROKER_CONSUMER
          valueFrom:
            configMapKeyRef:
              name: mcm-demo-config-map
              key: APP_KAFKA_BROKER_CONSUMER
        - name: APP_KAFKA_USERNAME
          valueFrom:
            configMapKeyRef:
              name: mcm-demo-config-map
              key: APP_KAFKA_USERNAME
        - name: APP_KAFKA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mcm-demo-secrets
              key: APP_KAFKA_PASSWORD
        - name: TZ
          value: Europe/Madrid
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
