apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcm-demo-consumer-customers-activation
  labels:
    k8s-app: mcm-demo-consumer-customers-activation
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: mcm-demo-consumer-customers-activation
  template:
    metadata:
      labels:
        k8s-app: mcm-demo-consumer-customers-activation
    spec:
      imagePullSecrets:
      - name: registrykey
      containers:
      - name: mcm-demo-consumer-customers-activation
        image: labcabrera/mcm-demo-consumer-customers-activation:latest
        envFrom:
        - configMapRef:
            name: mcm-demo-config-map-client-consumer
        - configMapRef:
            name: mcm-demo-config-map-kafka
        - configMapRef:
            name: mcm-demo-config-map-keycloak
        - secretRef:
            name: mcm-demo-secrets-client-consumer
        - secretRef:
            name: mcm-demo-secrets-kafka
        env:
        - name: APP_CUSTOMER_API_URL
          valueFrom:
            configMapKeyRef:
              name: mcm-demo-config-map
              key: APP_CUSTOMER_API_URL
        - name: TZ
          value: Europe/Madrid
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
