= MCM Demo REST Client

== Objetivo

* Pruebas integración Wildfly standalone
* Definición estructura DDD de paquetes
* POC de Code-First
* POC de Contract-First
* Integración seguridad (spring security)
* Integración módulos spring boot (data, cloud config, cloud stream, actuator, etc.)

Siguientes pasos:
* Dockerizar y desplegarla en k8s (minikube)
* Integración seguridad
* Gestion congfiguración ddbb


== Arranque de Wildfly

Utilizaremos una configuración preestablecida para de _standalone_ en la que hemos añadidos los
módulos de _MicroProfile_.

[source, bash]
----
./standalone.sh -c standalone-custom.xml
----

Una vez arrancado el servidor, podemos acceder a la consola de administración en:

http://localhost:9990/console/index.html#deployments


== Configuración de Keycloak

----
docker run -p 8090:8080 \
  -e KEYCLOAK_ADMIN=admin \
  -e KEYCLOAK_ADMIN_PASSWORD=admin \
  quay.io/keycloak/keycloak:24.0.3 \
  start-dev
----

Después crearemos el realm "mcm-demo" y el cliente guardando las credenciales.

waR7EFtFuz6uZtQACPmVmhqI7pAGDX21

----

./standalone.sh -c standalone-microprofile.xml

curl http://127.0.0.1:8080/demo/api/customers

curl http://127.0.0.1:8080/demo/api/customers/1 -v

curl http://127.0.0.1:8080/demo/api/customers/2 -v

curl http://127.0.0.1:8080/demo/api/customers -v

curl -X POST http://127.0.0.1:8080/demo/api/customers \
  -H "Content-Type: application/json" \
  -d '{
    "firstName": "John",
    "lastName": "Doe",
    "email": "john.doe@example.com"
}'

http://127.0.0.1:8080/demo/api/hello
http://127.0.0.1:8080/demo/hello.xhtml

mvn wildfly:deploy
mvn wildfly:undeploy
----


== Estructura de paquetes

- Domain: entidades del dominio (no las entidades JPA) y servicios con la lógica del negocio.º

- Application: clases de aplicación que implementan la lógica del negocio y delegan en los servicios del dominio. Estas clases no deberían tener mucha lógica, sino que deberían delegar en los servicios del dominio.

- Infrastructure: clases de infraestructura que implementan la lógica de acceso a datos, como repositorios, adaptadores y servicios externos.

https://github.com/wildfly/wildfly-s2i/tree/main/examples/jsf-ejb-jpa/src/main/java/org/wildfly/plugins/demo/jsf