apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcm-demo-ui-jsf
  labels:
    k8s-app: mcm-demo-ui-jsf
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: mcm-demo-ui-jsf
  template:
    metadata:
      labels:
        k8s-app: mcm-demo-ui-jsf
    spec:
      imagePullSecrets:
      - name: registrykey
      containers:
      - name: mcm-demo-ui-jsf
        image: labcabrera/mcm-demo-ui-jsf:latest
        env:
        - name: CUSTOMER_API_URL
          valueFrom:
            configMapKeyRef:
              name: mcm-demo-config-map
              key: CUSTOMER_API_URL
        - name: TOKEN_URL
          valueFrom:
            configMapKeyRef:
              name: mcm-demo-config-map
              key: TOKEN_URL
        - name: JWK_URL
          valueFrom:
            configMapKeyRef:
              name: mcm-demo-config-map
              key: JWK_URI
        - name: CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: mcm-demo-config-map
              key: CLIENT_ID
        - name: AUTH_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: mcm-demo-config-map
              key: AUTH_SERVER_URL
        - name: LOGOUT_URL
          valueFrom:
            configMapKeyRef:
              name: mcm-demo-config-map
              key: LOGOUT_URL
        - name: LOGIN_REDIRECT_URL
          valueFrom:
            configMapKeyRef:
              name: mcm-demo-config-map
              key: LOGIN_REDIRECT_URL
        - name: CALLBACK_URL
          valueFrom:
            configMapKeyRef:
              name: mcm-demo-config-map
              key: CALLBACK_URL
        - name: LOGOUT_REDIRECT_URL
          valueFrom:
            configMapKeyRef:
              name: mcm-demo-config-map
              key: LOGOUT_REDIRECT_URL
        - name: SCOPE
          valueFrom:
            configMapKeyRef:
              name: mcm-demo-config-map
              key: SCOPE
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: mcm-demo-secrets
              key: CLIENT_SECRET
        - name: TZ
          value: Europe/Madrid
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
