apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcm-demo-ui-jsf
  labels:
    k8s-app: mcm-demo-ui-jsf
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: mcm-demo-ui-jsf
  template:
    metadata:
      labels:
        k8s-app: mcm-demo-ui-jsf
    spec:
      imagePullSecrets:
      - name: registrykey
      containers:
      - name: mcm-demo-ui-jsf
        image: labcabrera/mcm-demo-ui-jsf:latest
        envFrom:
        - configMapRef:
            name: mcm-demo-config-map-client-jsf
        - configMapRef:
            name: mcm-demo-config-map-kafka
        - configMapRef:
            name: mcm-demo-config-map-db
        - configMapRef:
            name: mcm-demo-config-map
        - secretRef:
            name: mcm-demo-secrets-client-jsf
        - secretRef:
            name: mcm-demo-secrets-kafka
        - secretRef:
            name: mcm-demo-secrets-db
        env:
        - name: TZ
          value: Europe/Madrid
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
