@startuml Demo Authorization Flow - C4 Context
title Demo Authorization Flow - C4 Context

!include ./c4-context-system-shared.puml

LAYOUT_LEFT_RIGHT()

LAYOUT_WITH_LEGEND()

Person(user, "User")

Boundary(k8s, "Kubernetes") {
    Boundary(namespace_mcm_demo, "Namespace mcm-demo") {
        Boundary(wildfly_customer_api, "Wildfly Standalone Microprofile") {
            System(customer_api, "Customer API", "Jakarta 10")
            System_Ext(db, "Database", "Memory")
        }
        Boundary(wildfly_customer_fe, "Wildfly Standalone") {
            System(customer_fe, "Customer Frontend", "Jakarta 10 + JSF", $sprite="java", $tags="java")
        }
        Boundary(wildfly_user_api, "Wildfly Standalone Microprofile") {
            System(user_api, "User API", "Jakarta 10", $sprite="java", $tags="System")
        }
    }
}

System_Ext(keycloak, "Keycloak", "24.x", $tags="System_Ext")
System_Ext(kafka, "Kafka", "3.x", $tags="System_Ext")

Rel(user, customer_fe, "1.- Request resource", "HTTP / OIDC")

Rel(customer_fe, keycloak, "2.- Login redirect", "HTTP / OIDC")

Rel(keycloak, customer_fe, "3.- Callback with code", "HTTP / OIDC")

Rel(customer_fe, keycloak, "4.- Request token access", "HTTP / OIDC")

Rel(customer_fe, customer_api, "5.- API call with access token", "HTTPS")

Rel(customer_api, db, "JDBC")
Rel(customer_api, kafka, "Event")

Rel(customer_fe, user_api, "User mapping", "HTTP")
Rel(customer_api, user_api, "User mapping", "HTTP")

@enduml
