@startuml C4 Context Demo
title C4 Context Demo

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_LEFT_RIGHT()

UpdateElementStyle(person, $bgColor="#008fb3")
UpdateElementStyle(system, $bgColor="#f9b000")
UpdateElementStyle(external_system, $bgColor="#005b72")
UpdateElementStyle(boundary, $bgColor="#e6f8fa")

Person(user, "User")

Boundary(k8s, "Kubernetes (Minikube)") {
    Boundary(namespace_mcm_local, "Namespace apps-local", "", $tags="k8s_namespace") {
        System(customer_api, "Customer API", "Jakarta 10")
        System(customer_fe, "Customer Frontend", "Jakarta 10 + JSF")
        System(user_api, "User API", "Jakarta 10")
        System(customer_consumer, "Consumer Customer Activation", "Spring Boot 3.x")
        ' System(customer_job, "Customer Job", "CronJob Python")
    }
    Boundary(namespace_mcm_local_kafka, "Namespace kafka-local") {
        Boundary(kafka_boundary, "Kafka 3.x") {
            System_Ext(kafka_created_consumer_topic, "user-created topic", "Topic", $tags="queue")
        }
        System_Ext(schema_registry, "Schema Registry")
    }
}

Boundary(localDockerNetwork, "Local Docker Network") {
    System_Ext(keycloak, "Keycloak", "24.x")
    System_Ext(postgres, "Postgres", "17.x")
}

Rel(user, customer_fe, "Request resource", "HTTP")

Rel(customer_fe, keycloak, "External login", "HTTP / OIDC")

Rel(customer_fe, customer_api, "API call with access token", "HTTP / JWT")

Rel(customer_api, postgres, "JDBC")
Rel(customer_api, kafka_created_consumer_topic, "Publish event", "AVRO")

Rel(customer_fe, user_api, "Override user mapping", "HTTP")
Rel(customer_api, user_api, "Override user mapping", "HTTP")

Rel(kafka_created_consumer_topic, customer_consumer, "Consume events", "Kafka", "#red")

Rel(customer_consumer, customer_api, "Update status", "REST / Client Credentials")

' Rel(customer_job, postgres, "Read pending")
' Rel(customer_job, kafka_created_consumer_topic, "Queue events", "AVRO")

SHOW_LEGEND()

@enduml
