!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!define COLOR_SYSTEM #f9b000
!define COLOR_SYSTEM_EXT #005b72

' ElementStyle WildflyBoundary {
'     BackgroundColor #D0E6F6
'     BorderColor #4682B4
' }

AddElementTag("api", $bgColor="green", $fontColor="white", $borderColor="darkgreen")
AddElementTag("legacy", $bgColor="#bd391e", $fontColor="white", $borderColor="darkgreen")
AddElementTag("new", $bgColor="#f9b000", $fontColor="white", $borderColor="white")
AddElementTag("dev", $bgColor="#84bc3a", $fontColor="white", $borderColor="white")
AddElementTag("remove", $bgColor="#2f0000", $fontColor="white", $borderColor="white")

AddElementTag("System", $bgColor=COLOR_SYSTEM, $fontColor="white", $borderColor="white")
AddElementTag("System_Ext", $bgColor=COLOR_SYSTEM_EXT, $fontColor="white", $borderColor="white")
AddElementTag("WildflyBoundary", $bgColor="#D0E6F6", $fontColor="white", $borderColor="white")