!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!define COLOR_SYSTEM #f9b000
!define COLOR_SYSTEM_EXT #005b72

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define DEVICONS2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5

!include DEVICONS/angular.puml
!include DEVICONS/java.puml
!include DEVICONS/javascript.puml

!include DEVICONS2/gitlab.puml

!include ../sprites/springboot.puml
!include ../sprites/webpack.puml
!include ../sprites/kubernetes.puml
!include ../sprites/kafka.puml
!include ../sprites/istio.puml
!include ../sprites/gateway.puml

AddElementTag("api", $bgColor="green", $fontColor="white", $borderColor="darkgreen")
AddElementTag("legacy", $bgColor="#bd391e", $fontColor="white", $borderColor="darkgreen")
AddElementTag("new", $bgColor="#f9b000", $fontColor="white", $borderColor="white")
AddElementTag("mc", $bgColor="#005b72", $fontColor="white", $borderColor="white")
AddElementTag("dev", $bgColor="#84bc3a", $fontColor="white", $borderColor="white")
AddElementTag("remove", $bgColor="#2f0000", $fontColor="white", $borderColor="white")


AddElementTag("System", $bgColor=COLOR_SYSTEM, $fontColor="white", $borderColor="white")
AddElementTag("System_Ext", $bgColor=COLOR_SYSTEM_EXT, $fontColor="white", $borderColor="white")

'LAYOUT_TOP_DOWN()
LAYOUT_LEFT_RIGHT()
'LAYOUT_LANDSCAPE()

'LAYOUT_WITH_LEGEND()
HIDE_STEREOTYPE()