#!/bin/bash

NAMESPACE="mcm-local"

minikube start

#kubectl patch serviceaccount default -p '{"imagePullSecrets": [{"name": "regcred"}]}' -n mcm-dev

minikube addons enable metrics-server

# Install Ingress

minikube addons enable ingress

# Basic configMaps and secrets for the demo

echo "✨ Creating namespace "$NAMESPACE" and installing configMaps and secrets..."

kubectl create namespace "$NAMESPACE"

kubectl apply -f mcm-demo-config-map.yaml -n "$NAMESPACE"

kubectl apply -f mcm-demo-secrets.yaml -n "$NAMESPACE"

# Install Kafka

echo "✨ Installing Kafka using NodePort..."

helm install kafka bitnami/kafka \
  --namespace mcm-local-kafka \
  --create-namespace \
  --set externalAccess.enabled=true \
  --set externalAccess.controller.service.type=NodePort \
  --set externalAccess.broker.service.type=NodePort \
  --set defaultInitContainers.autoDiscovery.enabled=true \
  --set serviceAccount.create=true \
  --set rbac.create=true \
  --set controller.automountServiceAccountToken=true \
  --set broker.automountServiceAccountToken=true

# Update kafka autogenerated value in our demo namespace secrets

KAFKA_CLIENT_PWD=$(kubectl get secret kafka-user-passwords -n mcm-local-kafka -o jsonpath="{.data.client-passwords}")
kubectl patch secret mcm-demo-secrets -n mcm-local --type='merge' -p '{"data":{"APP_KAFKA_PASSWORD":"'"$KAFKA_CLIENT_PWD"'"}}'

echo "✨ Installing ArgoCD and configuring demo applications..."

# Install ArgoCD with fixed admin password 'changeit'

helm install argocd argo/argo-cd \
  --namespace argocd \
  --create-namespace \
  --set server.service.type=NodePort \
  --set configs.secret.argocdServerAdminPassword='$2y$10$vAKJfNlItZH/h500v0DObOd5IFBAUJifgSLTiVpKzqJ2AKGhqozVy'

# Create ArgoCD applications

kubectl apply -f ../argocd/mcm-demo-api-customers-app.yaml -n argocd

kubectl apply -f ../argocd/mcm-demo-api-users-app.yaml -n argocd

kubectl apply -f ../argocd/mcm-demo-ui-jsf-app.yaml -n argocd

kubectl apply -f ../argocd/mcm-demo-consumer-customers-activation-app.yaml -n argocd

kubectl get secret kafka-user-passwords -n mcm-local-kafka -o jsonpath="{.data.client-passwords}" | base64 -d

# Install Kafka UI

# TODO fix hardcoded user:pwd in configMap

kubectl apply -f kafka-ui-config.yaml -n mcm-local-kafka

helm install kafka-ui kafka-ui/kafka-ui \
  --set existingConfigMap="kafka-ui-config" \
  --set ingress.enabled=true \
  --set ingress.className=nginx \
  --set ingress.hosts[0].host=kafka-ui.local \
  --set ingress.hosts[0].paths[0].path=/ \
  --set ingress.hosts[0].paths[0].pathType=Prefix \
  --namespace mcm-local-kafka