#!/bin/bash

NAMESPACE="apps-local"
NAMESPACE_KAFKA="kafka-local"
NAMESPACE_DB="db-local"
NAMESPACE_TOOLS="tools-local"

minikube start --driver=docker --memory=12288

minikube addons enable metrics-server

# Install Ingress

minikube addons enable ingress

# Install Kafka

echo "✨ Installing Kafka using NodePort..."

helm install kafka bitnami/kafka \
  --namespace "$NAMESPACE_KAFKA" \
  --create-namespace \
  --set externalAccess.enabled=true \
  --set externalAccess.controller.service.type=NodePort \
  --set externalAccess.broker.service.type=NodePort \
  --set defaultInitContainers.autoDiscovery.enabled=true \
  --set serviceAccount.create=true \
  --set rbac.create=true \
  --set controller.automountServiceAccountToken=true \
  --set broker.automountServiceAccountToken=true

# Update kafka autogenerated value in our demo namespace secrets

KAFKA_CLIENT_PWD=$(kubectl get secret kafka-user-passwords -n "$NAMESPACE_KAFKA" -o jsonpath="{.data.client-passwords}")
KAFKA_CLIENT_PWD_DECODED=$(echo "$KAFKA_CLIENT_PWD" | base64 -d)

# Install Kafka Schema Registry

helm install schema-registry bitnami/schema-registry \
  --namespace "$NAMESPACE_KAFKA" \
  --set kafka.enabled=false \
  --set externalKafka.brokers=SASL_PLAINTEXT://kafka.kafka-local:9092 \
  --set externalKafka.auth.protocol=sasl \
  --set ingress.enabled=true \
  --set ingress.hostname=schema-registry.local \
  --set extraEnvVars[0].name=SCHEMA_REGISTRY_KAFKA_SASL_USER \
  --set extraEnvVars[0].value=user1 \
  --set extraEnvVars[1].name=SCHEMA_REGISTRY_KAFKA_SASL_PASSWORD \
  --set extraEnvVars[1].value="$KAFKA_CLIENT_PWD_DECODED"

# Basic configMaps and secrets for the demo

echo "✨ Creating namespace "$NAMESPACE" and installing configMaps and secrets..."

kubectl create namespace "$NAMESPACE"

find ../k8s-config-maps -name "*.yaml" -o -name "*.yml" | while read -r file; do
  kubectl apply -f "$file" -n "$NAMESPACE"
done

find ../k8s-secrets -name "*.yaml" -o -name "*.yml" | while read -r file; do
  sed "s/{kafka_password_b64}/$KAFKA_CLIENT_PWD/g" "$file" | kubectl apply -f - -n "$NAMESPACE_KAFKA"
done

echo "✨ Installing ArgoCD and configuring demo applications..."

# Install ArgoCD with fixed admin password 'changeit'

helm install argocd argo/argo-cd \
  --namespace "$NAMESPACE_TOOLS" \
  --create-namespace \
  --set server.service.type=NodePort \
  --set configs.secret.argocdServerAdminPassword='$2y$10$vAKJfNlItZH/h500v0DObOd5IFBAUJifgSLTiVpKzqJ2AKGhqozVy'

# Create ArgoCD applications

find ../argocd -name "*.yaml" -o -name "*.yml" | while read -r file; do
  kubectl apply -f "$file" -n "$NAMESPACE_TOOLS"
done

# Install Kafka UI

sed "s/{password}/$KAFKA_CLIENT_PWD_DECODED/g" kafka-ui-config.yaml | kubectl apply -f - -n "$NAMESPACE_KAFKA"

helm install kafka-ui kafka-ui/kafka-ui \
  --namespace "$NAMESPACE_KAFKA" \
  --set existingConfigMap="kafka-ui-config" \
  --set ingress.enabled=true \
  --set ingress.className=nginx \
  --set ingress.hosts[0].host=kafka-ui.local \
  --set ingress.hosts[0].paths[0].path=/ \
  --set ingress.hosts[0].paths[0].pathType=Prefix
