#!/bin/bash

NAMESPACE="apps-local"
NAMESPACE_KAFKA="kafka-local"
NAMESPACE_DB="db-local"
NAMESPACE_TOOLS="tools-local"

minikube start --driver=docker --memory=12288

#kubectl patch serviceaccount default -p '{"imagePullSecrets": [{"name": "regcred"}]}' -n mcm-dev

minikube addons enable metrics-server

# Install Ingress

minikube addons enable ingress

# Basic configMaps and secrets for the demo

echo "✨ Creating namespace "$NAMESPACE" and installing configMaps and secrets..."

kubectl create namespace "$NAMESPACE"

kubectl apply -f mcm-demo-config-map.yaml -n "$NAMESPACE"

kubectl apply -f mcm-demo-secrets.yaml -n "$NAMESPACE"

# Install PostgreSQL

helm install postgresql bitnami/postgresql \
  --namespace "$NAMESPACE_DB" \
  --set auth.postgresPassword=admin123 \
  --set auth.database=mcm_demo \
  --set auth.username=mcm_user \
  --set auth.password=mcm_pass \
  --set primary.persistence.enabled=true \
  --set primary.persistence.size=8Gi \
  --set primary.resources.requests.memory=256Mi \
  --set primary.resources.requests.cpu=250m \
  --set primary.resources.limits.memory=512Mi \
  --set primary.resources.limits.cpu=500m \
  --set metrics.enabled=true \
  --set metrics.serviceMonitor.enabled=false \
  --wait --timeout=300s

# Install Kafka

echo "✨ Installing Kafka using NodePort..."

helm install kafka bitnami/kafka \
  --namespace "$NAMESPACE_KAFKA" \
  --create-namespace \
  --set externalAccess.enabled=true \
  --set externalAccess.controller.service.type=NodePort \
  --set externalAccess.broker.service.type=NodePort \
  --set defaultInitContainers.autoDiscovery.enabled=true \
  --set serviceAccount.create=true \
  --set rbac.create=true \
  --set controller.automountServiceAccountToken=true \
  --set broker.automountServiceAccountToken=true

# Update kafka autogenerated value in our demo namespace secrets

KAFKA_CLIENT_PWD=$(kubectl get secret kafka-user-passwords -n "$NAMESPACE_KAFKA" -o jsonpath="{.data.client-passwords}")
kubectl patch secret mcm-demo-secrets -n "$NAMESPACE" --type='merge' -p '{"data":{"APP_KAFKA_PASSWORD":"'"$KAFKA_CLIENT_PWD"'"}}'

# Install Kafka Schema Registry

helm install schema-registry bitnami/schema-registry \
  --namespace "$NAMESPACE_KAFKA" \
  --set kafka.enabled=false \
  --set externalKafka.brokers=SASL_PLAINTEXT://kafka.kafka-local:9092 \
  --set externalKafka.auth.protocol=sasl \
  --set ingress.enabled=true \
  --set ingress.hostname=schema-registry.local \
  --set extraEnvVars[0].name=SCHEMA_REGISTRY_KAFKA_SASL_USER \
  --set extraEnvVars[0].value=user1 \
  --set extraEnvVars[1].name=SCHEMA_REGISTRY_KAFKA_SASL_PASSWORD \
  --set extraEnvVars[1].value="$KAFKA_CLIENT_PWD"

echo "✨ Installing ArgoCD and configuring demo applications..."

# Install ArgoCD with fixed admin password 'changeit'

helm install argocd argo/argo-cd \
  --namespace "$NAMESPACE_TOOLS" \
  --create-namespace \
  --set server.service.type=NodePort \
  --set configs.secret.argocdServerAdminPassword='$2y$10$vAKJfNlItZH/h500v0DObOd5IFBAUJifgSLTiVpKzqJ2AKGhqozVy'

# Create ArgoCD applications

kubectl apply -f ../argocd/mcm-demo-api-customers-app.yaml -n "$NAMESPACE_TOOLS"

kubectl apply -f ../argocd/mcm-demo-api-users-app.yaml -n "$NAMESPACE_TOOLS"

kubectl apply -f ../argocd/mcm-demo-ui-jsf-app.yaml -n "$NAMESPACE_TOOLS"

kubectl apply -f ../argocd/mcm-demo-consumer-customers-activation-app.yaml -n "$NAMESPACE_TOOLS"

kubectl apply -f ../argocd/mcm-demo-job-customers.yaml -n "$NAMESPACE_TOOLS"

# Install Kafka UI

sed "s/{password}/$KAFKA_CLIENT_PWD/g" kafka-ui-config.yaml | kubectl apply -f - -n "$NAMESPACE_KAFKA"

helm install kafka-ui kafka-ui/kafka-ui \
  --namespace "$NAMESPACE_KAFKA" \
  --set existingConfigMap="kafka-ui-config" \
  --set ingress.enabled=true \
  --set ingress.className=nginx \
  --set ingress.hosts[0].host=kafka-ui.local \
  --set ingress.hosts[0].paths[0].path=/ \
  --set ingress.hosts[0].paths[0].pathType=Prefix
