apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: my-kafka
  namespace: confluent
spec:
  replicas: 3
  kafka:
    image: confluentinc/cp-server:7.9.1
    config:
      "confluent.support.metrics.enable": "false"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    image: confluentinc/cp-zookeeper:7.9.1
    storage:
      type: ephemeral
