apiVersion: v1
kind: ConfigMap
metadata:
  name: mcm-demo-config-map
  namespace: mcm-dev
data:
  JWK_URI: http://host.minikube.internal:8090/realms/mcm-demo/protocol/openid-connect/certs
  FOO: foo-value
  BAR: bar-value