apiVersion: v1
kind: ConfigMap
metadata:
  name: mcm-demo-config-map
data:
  APP_AUTH_SERVER_URL: http://127.0.0.1:8090/realms/mcm-demo/protocol/openid-connect/auth
  APP_LOGOUT_URL: http://127.0.0.1:8090/realms/mcm-demo/protocol/openid-connect/logout

  APP_CUSTOMER_API_URL: http://mcm-demo-api-customers/api-customers
  APP_USERS_API_URL: http://mcm-demo-api-users/api-users/api

  APP_JWK_URL: http://host.minikube.internal:8090/realms/mcm-demo/protocol/openid-connect/certs
  APP_TOKEN_URL: http://host.minikube.internal:8090/realms/mcm-demo/protocol/openid-connect/token

  APP_LOGIN_REDIRECT_URL: http://mcm-demo-ui-jsf.local/demo-ui
  APP_CALLBACK_URL: http://mcm-demo-ui-jsf.local/demo-ui/callback
  APP_LOGOUT_REDIRECT_URL: http://mcm-demo-ui-jsf.local/demo-ui

  APP_CLIENT_ID: mcm-demo-client-jsf
  APP_OIDC_SCOPE: openid profile roles

  APP_KAFKA_BROKER: kafka.mcm-local-kafka.svc.cluster.local:9092
  APP_KAFKA_USERNAME: user1
  
  APP_KAFKA_TOPIC_CUSTOMER_CREATED: customers-created-topic

  APP_DB_HOST: host.minikube.internal
  APP_DB_PORT: "5432"
  APP_DB_SCHEMA: mcmdemo
  APP_DB_USERNAME: user
