mp.openapi.extensions.enabled=true

mp.openapi.info.title=MCM - Demo REST API de Clientes
mp.openapi.info.version=1.0.0
mp.openapi.info.description=API REST para la gestión de clientes, ejemplo con Jakarta EE y MicroProfile.
mp.openapi.info.termsOfService=https://samples.com/terminos
mp.openapi.info.contact.name=Equipo de Soporte
mp.openapi.info.contact.email=soporte@samples.com
mp.openapi.info.contact.url=https://samples.com/soporte
mp.openapi.info.license.name=MIT
mp.openapi.info.license.url=https://opensource.org/licenses/MIT