apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcm-demo-api-customers
  labels:
    k8s-app: mcm-demo-api-customers
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: mcm-demo-api-customers
  template:
    metadata:
      labels:
        k8s-app: mcm-demo-api-customers
    spec:
      imagePullSecrets:
      - name: registrykey
      containers:
      - name: mcm-demo-api-customers
        image: labcabrera/mcm-demo-api-customers:latest
        env:
        - name: APP_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mcm-demo-config-map
              key: APP_DB_HOST
        - name: APP_DB_PORT
          valueFrom:
            configMapKeyRef:
              name: mcm-demo-config-map
              key: APP_DB_PORT
        - name: APP_DB_SCHEMA
          valueFrom:
            configMapKeyRef:
              name: mcm-demo-config-map
              key: APP_DB_SCHEMA
        - name: APP_DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: mcm-demo-config-map
              key: APP_DB_USERNAME
        - name: APP_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mcm-demo-secrets
              key: APP_DB_PASSWORD
        - name: APP_USERS_API_URL
          valueFrom:
            configMapKeyRef:
              name: mcm-demo-config-map
              key: APP_USERS_API_URL
        - name: APP_JWK_URL
          valueFrom:
            configMapKeyRef:
              name: mcm-demo-config-map
              key: APP_JWK_URL
        - name: APP_KAFKA_BROKER
          valueFrom:
            configMapKeyRef:
              name: mcm-demo-config-map
              key: APP_KAFKA_BROKER
        - name: APP_KAFKA_USERNAME
          valueFrom:
            configMapKeyRef:
              name: mcm-demo-config-map
              key: APP_KAFKA_USERNAME
        - name: APP_KAFKA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mcm-demo-secrets
              key: APP_KAFKA_PASSWORD
        - name: APP_KAFKA_TOPIC_CUSTOMER_CREATED
          valueFrom:
            configMapKeyRef:
              name: mcm-demo-config-map
              key: APP_KAFKA_TOPIC_CUSTOMER_CREATED
        - name: TZ
          value: Europe/Madrid
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
