apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcm-demo-api-customers
  labels:
    k8s-app: mcm-demo-api-customers
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: mcm-demo-api-customers
  template:
    metadata:
      labels:
        k8s-app: mcm-demo-api-customers
    spec:
      imagePullSecrets:
      - name: registrykey
      containers:
      - name: mcm-demo-api-customers
        image: labcabrera/mcm-demo-api-customers:latest
        env:
        - name: JWK_URI
          valueFrom:
            configMapKeyRef:
              name: mcm-demo-config-map
              key: JWK_URI
        - name: TZ
          value: Europe/Madrid
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
