apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mcm-demo-api-customers
  annotations:
    kubernetes.io/ingress.class: nginx-ingress
spec:
  rules:
    - host: {{INGRESS_HOSTNAME}}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: mcm-demo-api-customers
                port:
                  number: 80
