#auth.server.url=http://localhost:8090/realms/mcm-demo/protocol/openid-connect/auth
#token.endpoint=http://localhost:8090/realms/mcm-demo/protocol/openid-connect/token
#cert.endpoint=http://localhost:8090/realms/mcm-demo/protocol/openid-connect/certs

#client.id=mcm-demo-client-jsf
#client.secret=HtsCdaR7o5KoNQpI0BOOWwtds1sxorCT

#base.url=http://localhost:8084/demo-ui
#redirect.uri=http://localhost:8084/demo-ui/callback
scope=openid profile roles